package mnj.mfg.model.views;

import mnj.mfg.model.entities.LineEOStyleDetailImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 14 15:56:47 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LineVOStyleDetailRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        GwpGeId {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getGwpGeId();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setGwpGeId((Number)value);
            }
        }
        ,
        GwpGeWaslineId {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getGwpGeWaslineId();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setGwpGeWaslineId((Number)value);
            }
        }
        ,
        GwpGeObid {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getGwpGeObid();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setGwpGeObid((Number)value);
            }
        }
        ,
        Salesorder {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getSalesorder();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setSalesorder((Number)value);
            }
        }
        ,
        SoLine {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getSoLine();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setSoLine((Number)value);
            }
        }
        ,
        GwpUnitId {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getGwpUnitId();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setGwpUnitId((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        ObsNo {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getObsNo();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setObsNo((String)value);
            }
        }
        ,
        Quantity {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getQuantity();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        PostStatus {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getPostStatus();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setPostStatus((String)value);
            }
        }
        ,
        JobStatus {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getJobStatus();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setJobStatus((String)value);
            }
        }
        ,
        WipEntityId {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getWipEntityId();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setWipEntityId((Number)value);
            }
        }
        ,
        JobReleasedDate {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getJobReleasedDate();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setJobReleasedDate((Date)value);
            }
        }
        ,
        WashName {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getWashName();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setWashName((String)value);
            }
        }
        ,
        WashingUnitName {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getWashingUnitName();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setWashingUnitName((String)value);
            }
        }
        ,
        WashingStartDate {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getWashingStartDate();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setWashingStartDate((Date)value);
            }
        }
        ,
        StitchingUnit {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getStitchingUnit();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setStitchingUnit((String)value);
            }
        }
        ,
        StitchingStartDate {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getStitchingStartDate();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setStitchingStartDate((Date)value);
            }
        }
        ,
        ViewShipmentDetail {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getViewShipmentDetail();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setViewShipmentDetail((String)value);
            }
        }
        ,
        TemCode {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getTemCode();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setTemCode((String)value);
            }
        }
        ,
        Description {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getDescription();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        ShipmentQty {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getShipmentQty();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setShipmentQty((Number)value);
            }
        }
        ,
        ShipmentDate {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getShipmentDate();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setShipmentDate((Date)value);
            }
        }
        ,
        CountryChange {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getCountryChange();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setCountryChange((String)value);
            }
        }
        ,
        ItemId {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getItemId();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        CurrentPlanQty {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getCurrentPlanQty();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setCurrentPlanQty((Number)value);
            }
        }
        ,
        JobName {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getJobName();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setJobName((String)value);
            }
        }
        ,
        BalanceQty {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getBalanceQty();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setBalanceQty((Number)value);
            }
        }
        ,
        OrderedQuantity {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getOrderedQuantity();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setOrderedQuantity((Number)value);
            }
        }
        ,
        BpoId {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getBpoId();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setBpoId((Number)value);
            }
        }
        ,
        StnLOV1 {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getStnLOV1();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItemCodeLov1 {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getItemCodeLov1();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WashingWorkArea1 {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getWashingWorkArea1();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StitchingWA1 {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getStitchingWA1();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        StnLovNewVO1 {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getStnLovNewVO1();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        STN_LOV_VO1 {
            public Object get(LineVOStyleDetailRowImpl obj) {
                return obj.getSTN_LOV_VO1();
            }

            public void put(LineVOStyleDetailRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(LineVOStyleDetailRowImpl object);

        public abstract void put(LineVOStyleDetailRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GWPGEID = AttributesEnum.GwpGeId.index();
    public static final int GWPGEWASLINEID = AttributesEnum.GwpGeWaslineId.index();
    public static final int GWPGEOBID = AttributesEnum.GwpGeObid.index();
    public static final int SALESORDER = AttributesEnum.Salesorder.index();
    public static final int SOLINE = AttributesEnum.SoLine.index();
    public static final int GWPUNITID = AttributesEnum.GwpUnitId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int OBSNO = AttributesEnum.ObsNo.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int POSTSTATUS = AttributesEnum.PostStatus.index();
    public static final int JOBSTATUS = AttributesEnum.JobStatus.index();
    public static final int WIPENTITYID = AttributesEnum.WipEntityId.index();
    public static final int JOBRELEASEDDATE = AttributesEnum.JobReleasedDate.index();
    public static final int WASHNAME = AttributesEnum.WashName.index();
    public static final int WASHINGUNITNAME = AttributesEnum.WashingUnitName.index();
    public static final int WASHINGSTARTDATE = AttributesEnum.WashingStartDate.index();
    public static final int STITCHINGUNIT = AttributesEnum.StitchingUnit.index();
    public static final int STITCHINGSTARTDATE = AttributesEnum.StitchingStartDate.index();
    public static final int VIEWSHIPMENTDETAIL = AttributesEnum.ViewShipmentDetail.index();
    public static final int TEMCODE = AttributesEnum.TemCode.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int SHIPMENTQTY = AttributesEnum.ShipmentQty.index();
    public static final int SHIPMENTDATE = AttributesEnum.ShipmentDate.index();
    public static final int COUNTRYCHANGE = AttributesEnum.CountryChange.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int CURRENTPLANQTY = AttributesEnum.CurrentPlanQty.index();
    public static final int JOBNAME = AttributesEnum.JobName.index();
    public static final int BALANCEQTY = AttributesEnum.BalanceQty.index();
    public static final int ORDEREDQUANTITY = AttributesEnum.OrderedQuantity.index();
    public static final int BPOID = AttributesEnum.BpoId.index();
    public static final int STNLOV1 = AttributesEnum.StnLOV1.index();
    public static final int ITEMCODELOV1 = AttributesEnum.ItemCodeLov1.index();
    public static final int WASHINGWORKAREA1 = AttributesEnum.WashingWorkArea1.index();
    public static final int STITCHINGWA1 = AttributesEnum.StitchingWA1.index();
    public static final int STNLOVNEWVO1 = AttributesEnum.StnLovNewVO1.index();
    public static final int STN_LOV_VO1 = AttributesEnum.STN_LOV_VO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LineVOStyleDetailRowImpl() {
    }

    /**
     * Gets LineEOStyleDetail entity object.
     * @return the LineEOStyleDetail
     */
    public LineEOStyleDetailImpl getLineEOStyleDetail() {
        return (LineEOStyleDetailImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for GWP_GE_ID using the alias name GwpGeId.
     * @return the GWP_GE_ID
     */
    public Number getGwpGeId() {
        return (Number) getAttributeInternal(GWPGEID);
    }

    /**
     * Sets <code>value</code> as attribute value for GWP_GE_ID using the alias name GwpGeId.
     * @param value value to set the GWP_GE_ID
     */
    public void setGwpGeId(Number value) {
        setAttributeInternal(GWPGEID, value);
    }

    /**
     * Gets the attribute value for GWP_GE_WASLINE_ID using the alias name GwpGeWaslineId.
     * @return the GWP_GE_WASLINE_ID
     */
    public Number getGwpGeWaslineId() {
        return (Number) getAttributeInternal(GWPGEWASLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for GWP_GE_WASLINE_ID using the alias name GwpGeWaslineId.
     * @param value value to set the GWP_GE_WASLINE_ID
     */
    public void setGwpGeWaslineId(Number value) {
        setAttributeInternal(GWPGEWASLINEID, value);
    }

    /**
     * Gets the attribute value for GWP_GE_OBID using the alias name GwpGeObid.
     * @return the GWP_GE_OBID
     */
    public Number getGwpGeObid() {
        return (Number) getAttributeInternal(GWPGEOBID);
    }

    /**
     * Sets <code>value</code> as attribute value for GWP_GE_OBID using the alias name GwpGeObid.
     * @param value value to set the GWP_GE_OBID
     */
    public void setGwpGeObid(Number value) {
        setAttributeInternal(GWPGEOBID, value);
    }

    /**
     * Gets the attribute value for SALESORDER using the alias name Salesorder.
     * @return the SALESORDER
     */
    public Number getSalesorder() {
        return (Number) getAttributeInternal(SALESORDER);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESORDER using the alias name Salesorder.
     * @param value value to set the SALESORDER
     */
    public void setSalesorder(Number value) {
        setAttributeInternal(SALESORDER, value);
    }

    /**
     * Gets the attribute value for SO_LINE using the alias name SoLine.
     * @return the SO_LINE
     */
    public Number getSoLine() {
        return (Number) getAttributeInternal(SOLINE);
    }

    /**
     * Sets <code>value</code> as attribute value for SO_LINE using the alias name SoLine.
     * @param value value to set the SO_LINE
     */
    public void setSoLine(Number value) {
        setAttributeInternal(SOLINE, value);
    }

    /**
     * Gets the attribute value for GWP_UNIT_ID using the alias name GwpUnitId.
     * @return the GWP_UNIT_ID
     */
    public String getGwpUnitId() {
        return (String) getAttributeInternal(GWPUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for GWP_UNIT_ID using the alias name GwpUnitId.
     * @param value value to set the GWP_UNIT_ID
     */
    public void setGwpUnitId(String value) {
        setAttributeInternal(GWPUNITID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for OBS_NO using the alias name ObsNo.
     * @return the OBS_NO
     */
    public String getObsNo() {
        return (String) getAttributeInternal(OBSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for OBS_NO using the alias name ObsNo.
     * @param value value to set the OBS_NO
     */
    public void setObsNo(String value) {
        setAttributeInternal(OBSNO, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Number getQuantity() {
        return (Number) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for POST_STATUS using the alias name PostStatus.
     * @return the POST_STATUS
     */
    public String getPostStatus() {
        return (String) getAttributeInternal(POSTSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for POST_STATUS using the alias name PostStatus.
     * @param value value to set the POST_STATUS
     */
    public void setPostStatus(String value) {
        setAttributeInternal(POSTSTATUS, value);
    }

    /**
     * Gets the attribute value for JOB_STATUS using the alias name JobStatus.
     * @return the JOB_STATUS
     */
    public String getJobStatus() {
        return (String) getAttributeInternal(JOBSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_STATUS using the alias name JobStatus.
     * @param value value to set the JOB_STATUS
     */
    public void setJobStatus(String value) {
        setAttributeInternal(JOBSTATUS, value);
    }

    /**
     * Gets the attribute value for WIP_ENTITY_ID using the alias name WipEntityId.
     * @return the WIP_ENTITY_ID
     */
    public Number getWipEntityId() {
        return (Number) getAttributeInternal(WIPENTITYID);
    }

    /**
     * Sets <code>value</code> as attribute value for WIP_ENTITY_ID using the alias name WipEntityId.
     * @param value value to set the WIP_ENTITY_ID
     */
    public void setWipEntityId(Number value) {
        setAttributeInternal(WIPENTITYID, value);
    }

    /**
     * Gets the attribute value for JOB_RELEASED_DATE using the alias name JobReleasedDate.
     * @return the JOB_RELEASED_DATE
     */
    public Date getJobReleasedDate() {
        return (Date) getAttributeInternal(JOBRELEASEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_RELEASED_DATE using the alias name JobReleasedDate.
     * @param value value to set the JOB_RELEASED_DATE
     */
    public void setJobReleasedDate(Date value) {
        setAttributeInternal(JOBRELEASEDDATE, value);
    }

    /**
     * Gets the attribute value for WASH_NAME using the alias name WashName.
     * @return the WASH_NAME
     */
    public String getWashName() {
        return (String) getAttributeInternal(WASHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_NAME using the alias name WashName.
     * @param value value to set the WASH_NAME
     */
    public void setWashName(String value) {
        setAttributeInternal(WASHNAME, value);
    }

    /**
     * Gets the attribute value for WASHING_UNIT_NAME using the alias name WashingUnitName.
     * @return the WASHING_UNIT_NAME
     */
    public String getWashingUnitName() {
        return (String) getAttributeInternal(WASHINGUNITNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for WASHING_UNIT_NAME using the alias name WashingUnitName.
     * @param value value to set the WASHING_UNIT_NAME
     */
    public void setWashingUnitName(String value) {
        setAttributeInternal(WASHINGUNITNAME, value);
    }

    /**
     * Gets the attribute value for WASHING_START_DATE using the alias name WashingStartDate.
     * @return the WASHING_START_DATE
     */
    public Date getWashingStartDate() {
        return (Date) getAttributeInternal(WASHINGSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for WASHING_START_DATE using the alias name WashingStartDate.
     * @param value value to set the WASHING_START_DATE
     */
    public void setWashingStartDate(Date value) {
        setAttributeInternal(WASHINGSTARTDATE, value);
    }

    /**
     * Gets the attribute value for STITCHING_UNIT using the alias name StitchingUnit.
     * @return the STITCHING_UNIT
     */
    public String getStitchingUnit() {
        return (String) getAttributeInternal(STITCHINGUNIT);
    }

    /**
     * Sets <code>value</code> as attribute value for STITCHING_UNIT using the alias name StitchingUnit.
     * @param value value to set the STITCHING_UNIT
     */
    public void setStitchingUnit(String value) {
        setAttributeInternal(STITCHINGUNIT, value);
    }

    /**
     * Gets the attribute value for STITCHING_START_DATE using the alias name StitchingStartDate.
     * @return the STITCHING_START_DATE
     */
    public Date getStitchingStartDate() {
        return (Date) getAttributeInternal(STITCHINGSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STITCHING_START_DATE using the alias name StitchingStartDate.
     * @param value value to set the STITCHING_START_DATE
     */
    public void setStitchingStartDate(Date value) {
        setAttributeInternal(STITCHINGSTARTDATE, value);
    }

    /**
     * Gets the attribute value for VIEW_SHIPMENT_DETAIL using the alias name ViewShipmentDetail.
     * @return the VIEW_SHIPMENT_DETAIL
     */
    public String getViewShipmentDetail() {
        return (String) getAttributeInternal(VIEWSHIPMENTDETAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for VIEW_SHIPMENT_DETAIL using the alias name ViewShipmentDetail.
     * @param value value to set the VIEW_SHIPMENT_DETAIL
     */
    public void setViewShipmentDetail(String value) {
        setAttributeInternal(VIEWSHIPMENTDETAIL, value);
    }

    /**
     * Gets the attribute value for TEM_CODE using the alias name TemCode.
     * @return the TEM_CODE
     */
    public String getTemCode() {
        return (String) getAttributeInternal(TEMCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TEM_CODE using the alias name TemCode.
     * @param value value to set the TEM_CODE
     */
    public void setTemCode(String value) {
        setAttributeInternal(TEMCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_QTY using the alias name ShipmentQty.
     * @return the SHIPMENT_QTY
     */
    public Number getShipmentQty() {
        return (Number) getAttributeInternal(SHIPMENTQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_QTY using the alias name ShipmentQty.
     * @param value value to set the SHIPMENT_QTY
     */
    public void setShipmentQty(Number value) {
        setAttributeInternal(SHIPMENTQTY, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_DATE using the alias name ShipmentDate.
     * @return the SHIPMENT_DATE
     */
    public Date getShipmentDate() {
        return (Date) getAttributeInternal(SHIPMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_DATE using the alias name ShipmentDate.
     * @param value value to set the SHIPMENT_DATE
     */
    public void setShipmentDate(Date value) {
        setAttributeInternal(SHIPMENTDATE, value);
    }

    /**
     * Gets the attribute value for COUNTRY_CHANGE using the alias name CountryChange.
     * @return the COUNTRY_CHANGE
     */
    public String getCountryChange() {
        return (String) getAttributeInternal(COUNTRYCHANGE);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_CHANGE using the alias name CountryChange.
     * @param value value to set the COUNTRY_CHANGE
     */
    public void setCountryChange(String value) {
        setAttributeInternal(COUNTRYCHANGE, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public Number getItemId() {
        return (Number) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for CURRENT_PLAN_QTY using the alias name CurrentPlanQty.
     * @return the CURRENT_PLAN_QTY
     */
    public Number getCurrentPlanQty() {
        return (Number) getAttributeInternal(CURRENTPLANQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENT_PLAN_QTY using the alias name CurrentPlanQty.
     * @param value value to set the CURRENT_PLAN_QTY
     */
    public void setCurrentPlanQty(Number value) {
        setAttributeInternal(CURRENTPLANQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute JobName.
     * @return the JobName
     */
    public String getJobName() {
        return (String) getAttributeInternal(JOBNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute JobName.
     * @param value value to set the  JobName
     */
    public void setJobName(String value) {
        setAttributeInternal(JOBNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BalanceQty.
     * @return the BalanceQty
     */
    public Number getBalanceQty() {
        return (Number) getAttributeInternal(BALANCEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BalanceQty.
     * @param value value to set the  BalanceQty
     */
    public void setBalanceQty(Number value) {
        setAttributeInternal(BALANCEQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderedQuantity.
     * @return the OrderedQuantity
     */
    public Number getOrderedQuantity() {
        return (Number) getAttributeInternal(ORDEREDQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrderedQuantity.
     * @param value value to set the  OrderedQuantity
     */
    public void setOrderedQuantity(Number value) {
        setAttributeInternal(ORDEREDQUANTITY, value);
    }

    /**
     * Gets the attribute value for BPO_ID using the alias name BpoId.
     * @return the BPO_ID
     */
    public Number getBpoId() {
        return (Number) getAttributeInternal(BPOID);
    }

    /**
     * Sets <code>value</code> as attribute value for BPO_ID using the alias name BpoId.
     * @param value value to set the BPO_ID
     */
    public void setBpoId(Number value) {
        setAttributeInternal(BPOID, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StnLOV1.
     */
    public RowSet getStnLOV1() {
        return (RowSet)getAttributeInternal(STNLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemCodeLov1.
     */
    public RowSet getItemCodeLov1() {
        return (RowSet)getAttributeInternal(ITEMCODELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WashingWorkArea1.
     */
    public RowSet getWashingWorkArea1() {
        return (RowSet)getAttributeInternal(WASHINGWORKAREA1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StitchingWA1.
     */
    public RowSet getStitchingWA1() {
        return (RowSet)getAttributeInternal(STITCHINGWA1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StnLovNewVO1.
     */
    public RowSet getStnLovNewVO1() {
        return (RowSet)getAttributeInternal(STNLOVNEWVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> STN_LOV_VO1.
     */
    public RowSet getSTN_LOV_VO1() {
        return (RowSet)getAttributeInternal(STN_LOV_VO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
