package mnj.mfg.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 14 15:56:47 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LineVOStyleDetailImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LineVOStyleDetailImpl() {
    }
}
