package mnj.ont.model.services.client;

import mnj.ont.model.services.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 10 18:19:45 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public void findSelLines() {
        Object _ret = this.riInvokeExportedMethod(this,"findSelLines",null,null);
        return;
    }

    public void populateOrderLines(String saleOrderID) {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateOrderLines",new String [] {"java.lang.String"},new Object[] {saleOrderID});
        return;
    }

    public void setPopUpWhereClauseOperations() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setPopUpWhereClauseOperations",null,null);
        return;
    }

    public void populateOperations() {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateOperations",null,null);
        return;
    }

    public void populateBundlesStn() {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateBundlesStn",null,null);
        return;
    }

    public int VersionCreation() {
        Object _ret =
            this.riInvokeExportedMethod(this,"VersionCreation",null,null);
        return ((Integer)_ret).intValue();
    }

    public String createJob(int HeaderId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createJob",new String [] {"int"},new Object[] {new Integer(HeaderId)});
        return (String)_ret;
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public String createMaterial(int HeaderId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createMaterial",new String [] {"int"},new Object[] {new Integer(HeaderId)});
        return (String)_ret;
    }

    public String callCreateRouting(int inventoryID, int HeaderId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"callCreateRouting",new String [] {"int","int"},new Object[] {new Integer(inventoryID), new Integer(HeaderId)});
        return (String)_ret;
    }

    public String CreateRequisition() {
        Object _ret =
            this.riInvokeExportedMethod(this,"CreateRequisition",null,null);
        return (String)_ret;
    }

    public String callBOM(int inventoryID, int HeaderID) {
        Object _ret =
            this.riInvokeExportedMethod(this,"callBOM",new String [] {"int","int"},new Object[] {new Integer(inventoryID), new Integer(HeaderID)});
        return (String)_ret;
    }

    public void Populate() {
        Object _ret = this.riInvokeExportedMethod(this,"Populate",null,null);
        return;
    }

    public void checkduplication(String HeaderId, String BuyerId, String Style,
                                 String Season, String Wash, String Color) {
        Object _ret =
            this.riInvokeExportedMethod(this,"checkduplication",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {HeaderId, BuyerId, Style, Season, Wash, Color});
        return;
    }

    public void Delete_Header() {
        Object _ret = this.riInvokeExportedMethod(this,"Delete_Header",null,null);
        return;
    }

    public void DeleteStyleDetail() {
        Object _ret =
            this.riInvokeExportedMethod(this,"DeleteStyleDetail",null,null);
        return;
    }

    public String CallPost(int HeaderId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"CallPost",new String [] {"int"},new Object[] {new Integer(HeaderId)});
        return (String)_ret;
    }

    public String CallCompletion(int HeaderId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"CallCompletion",new String [] {"int"},new Object[] {new Integer(HeaderId)});
        return (String)_ret;
    }

    public String CreateMaterial(String inventoryID, String HeaderID) {
        Object _ret =
            this.riInvokeExportedMethod(this,"CreateMaterial",new String [] {"java.lang.String","java.lang.String"},new Object[] {inventoryID, HeaderID});
        return (String)_ret;
    }
}
