package mnj.mfg.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 08 12:06:21 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailRecipesEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        OperationId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getOperationId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setOperationId((Number)value);
            }
        }
        ,
        OperatLineId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getOperatLineId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setOperatLineId((Number)value);
            }
        }
        ,
        CompanyId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getCompanyId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setCompanyId((String)value);
            }
        }
        ,
        DivisionId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getDivisionId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        PlanId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getPlanId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setPlanId((String)value);
            }
        }
        ,
        ProcessId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getProcessId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setProcessId((Number)value);
            }
        }
        ,
        OcId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getOcId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setOcId((String)value);
            }
        }
        ,
        TcTopside {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getTcTopside();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setTcTopside((String)value);
            }
        }
        ,
        TcInside {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getTcInside();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setTcInside((String)value);
            }
        }
        ,
        MachineType {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getMachineType();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setMachineType((String)value);
            }
        }
        ,
        NoOfMachines {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getNoOfMachines();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setNoOfMachines((Number)value);
            }
        }
        ,
        FootId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getFootId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setFootId((String)value);
            }
        }
        ,
        GuageId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getGuageId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setGuageId((String)value);
            }
        }
        ,
        NoOfWp {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getNoOfWp();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setNoOfWp((Number)value);
            }
        }
        ,
        Smv {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getSmv();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setSmv((Number)value);
            }
        }
        ,
        UserId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getUserId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setUserId((String)value);
            }
        }
        ,
        UserDate {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getUserDate();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setUserDate((Date)value);
            }
        }
        ,
        TerminalId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getTerminalId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setTerminalId((String)value);
            }
        }
        ,
        LineNum {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getLineNum();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setLineNum((Number)value);
            }
        }
        ,
        Target {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getTarget();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setTarget((String)value);
            }
        }
        ,
        Points {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getPoints();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setPoints((Number)value);
            }
        }
        ,
        NdlTime {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getNdlTime();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setNdlTime((Number)value);
            }
        }
        ,
        TotTime {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getTotTime();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setTotTime((Number)value);
            }
        }
        ,
        SpInst {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getSpInst();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setSpInst((String)value);
            }
        }
        ,
        ResourceId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getResourceId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setResourceId((String)value);
            }
        }
        ,
        PMachineType {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getPMachineType();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setPMachineType((String)value);
            }
        }
        ,
        ResourceVal {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getResourceVal();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setResourceVal((Number)value);
            }
        }
        ,
        ResourceId2 {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getResourceId2();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setResourceId2((String)value);
            }
        }
        ,
        ResourceVal2 {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getResourceVal2();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setResourceVal2((Number)value);
            }
        }
        ,
        Dposted {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getDposted();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setDposted((String)value);
            }
        }
        ,
        TrgtGwp {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getTrgtGwp();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setTrgtGwp((Number)value);
            }
        }
        ,
        CmtQty {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getCmtQty();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setCmtQty((Number)value);
            }
        }
        ,
        CmtJobrate {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getCmtJobrate();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setCmtJobrate((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        OcType {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getOcType();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setOcType((String)value);
            }
        }
        ,
        MenPower {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getMenPower();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setMenPower((Number)value);
            }
        }
        ,
        WorkerType {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getWorkerType();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setWorkerType((String)value);
            }
        }
        ,
        SqNum {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getSqNum();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setSqNum((Number)value);
            }
        }
        ,
        ParentOprId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getParentOprId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setParentOprId((Number)value);
            }
        }
        ,
        OcErpCode {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getOcErpCode();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setOcErpCode((String)value);
            }
        }
        ,
        ComponentId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getComponentId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setComponentId((Number)value);
            }
        }
        ,
        StandardOperationCode {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getStandardOperationCode();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setStandardOperationCode((String)value);
            }
        }
        ,
        ProcessFlow {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getProcessFlow();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setProcessFlow((String)value);
            }
        }
        ,
        HelperSmv {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getHelperSmv();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setHelperSmv((Number)value);
            }
        }
        ,
        OperatOblineId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getOperatOblineId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setOperatOblineId((Number)value);
            }
        }
        ,
        EmbNoStitch {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getEmbNoStitch();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setEmbNoStitch((Number)value);
            }
        }
        ,
        SNo {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getSNo();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setSNo((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getHeaderId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        OpLineId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getOpLineId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setOpLineId((Number)value);
            }
        }
        ,
        ObLinesId {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getObLinesId();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setObLinesId((Number)value);
            }
        }
        ,
        GwpGeObid {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getGwpGeObid();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setGwpGeObid((Number)value);
            }
        }
        ,
        MinorOperations {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getMinorOperations();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setMinorOperations((String)value);
            }
        }
        ,
        MajorOperations {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getMajorOperations();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setMajorOperations((String)value);
            }
        }
        ,
        Water {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getWater();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setWater((String)value);
            }
        }
        ,
        Time {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getTime();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setTime((String)value);
            }
        }
        ,
        Sequence {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getSequence();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setSequence((String)value);
            }
        }
        ,
        WashType {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getWashType();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setWashType((String)value);
            }
        }
        ,
        Seq {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getSeq();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setSeq((Number)value);
            }
        }
        ,
        ChemiRecipiDetailEo {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getChemiRecipiDetailEo();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SubProcessEO {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getSubProcessEO();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        HederEO {
            public Object get(DetailRecipesEOImpl obj) {
                return obj.getHederEO();
            }

            public void put(DetailRecipesEOImpl obj, Object value) {
                obj.setHederEO((HederEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(DetailRecipesEOImpl object);

        public abstract void put(DetailRecipesEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int OPERATIONID = AttributesEnum.OperationId.index();
    public static final int OPERATLINEID = AttributesEnum.OperatLineId.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int PLANID = AttributesEnum.PlanId.index();
    public static final int PROCESSID = AttributesEnum.ProcessId.index();
    public static final int OCID = AttributesEnum.OcId.index();
    public static final int TCTOPSIDE = AttributesEnum.TcTopside.index();
    public static final int TCINSIDE = AttributesEnum.TcInside.index();
    public static final int MACHINETYPE = AttributesEnum.MachineType.index();
    public static final int NOOFMACHINES = AttributesEnum.NoOfMachines.index();
    public static final int FOOTID = AttributesEnum.FootId.index();
    public static final int GUAGEID = AttributesEnum.GuageId.index();
    public static final int NOOFWP = AttributesEnum.NoOfWp.index();
    public static final int SMV = AttributesEnum.Smv.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int USERDATE = AttributesEnum.UserDate.index();
    public static final int TERMINALID = AttributesEnum.TerminalId.index();
    public static final int LINENUM = AttributesEnum.LineNum.index();
    public static final int TARGET = AttributesEnum.Target.index();
    public static final int POINTS = AttributesEnum.Points.index();
    public static final int NDLTIME = AttributesEnum.NdlTime.index();
    public static final int TOTTIME = AttributesEnum.TotTime.index();
    public static final int SPINST = AttributesEnum.SpInst.index();
    public static final int RESOURCEID = AttributesEnum.ResourceId.index();
    public static final int PMACHINETYPE = AttributesEnum.PMachineType.index();
    public static final int RESOURCEVAL = AttributesEnum.ResourceVal.index();
    public static final int RESOURCEID2 = AttributesEnum.ResourceId2.index();
    public static final int RESOURCEVAL2 = AttributesEnum.ResourceVal2.index();
    public static final int DPOSTED = AttributesEnum.Dposted.index();
    public static final int TRGTGWP = AttributesEnum.TrgtGwp.index();
    public static final int CMTQTY = AttributesEnum.CmtQty.index();
    public static final int CMTJOBRATE = AttributesEnum.CmtJobrate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int OCTYPE = AttributesEnum.OcType.index();
    public static final int MENPOWER = AttributesEnum.MenPower.index();
    public static final int WORKERTYPE = AttributesEnum.WorkerType.index();
    public static final int SQNUM = AttributesEnum.SqNum.index();
    public static final int PARENTOPRID = AttributesEnum.ParentOprId.index();
    public static final int OCERPCODE = AttributesEnum.OcErpCode.index();
    public static final int COMPONENTID = AttributesEnum.ComponentId.index();
    public static final int STANDARDOPERATIONCODE = AttributesEnum.StandardOperationCode.index();
    public static final int PROCESSFLOW = AttributesEnum.ProcessFlow.index();
    public static final int HELPERSMV = AttributesEnum.HelperSmv.index();
    public static final int OPERATOBLINEID = AttributesEnum.OperatOblineId.index();
    public static final int EMBNOSTITCH = AttributesEnum.EmbNoStitch.index();
    public static final int SNO = AttributesEnum.SNo.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int OPLINEID = AttributesEnum.OpLineId.index();
    public static final int OBLINESID = AttributesEnum.ObLinesId.index();
    public static final int GWPGEOBID = AttributesEnum.GwpGeObid.index();
    public static final int MINOROPERATIONS = AttributesEnum.MinorOperations.index();
    public static final int MAJOROPERATIONS = AttributesEnum.MajorOperations.index();
    public static final int WATER = AttributesEnum.Water.index();
    public static final int TIME = AttributesEnum.Time.index();
    public static final int SEQUENCE = AttributesEnum.Sequence.index();
    public static final int WASHTYPE = AttributesEnum.WashType.index();
    public static final int SEQ = AttributesEnum.Seq.index();
    public static final int CHEMIRECIPIDETAILEO = AttributesEnum.ChemiRecipiDetailEo.index();
    public static final int SUBPROCESSEO = AttributesEnum.SubProcessEO.index();
    public static final int HEDEREO = AttributesEnum.HederEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DetailRecipesEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.DetailRecipesEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for OperationId, using the alias name OperationId.
     * @return the OperationId
     */
    public Number getOperationId() {
        return (Number)getAttributeInternal(OPERATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperationId.
     * @param value value to set the OperationId
     */
    public void setOperationId(Number value) {
        setAttributeInternal(OPERATIONID, value);
    }

    /**
     * Gets the attribute value for OperatLineId, using the alias name OperatLineId.
     * @return the OperatLineId
     */
    public Number getOperatLineId() {
        return (Number)getAttributeInternal(OPERATLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatLineId.
     * @param value value to set the OperatLineId
     */
    public void setOperatLineId(Number value) {
        setAttributeInternal(OPERATLINEID, value);
    }

    /**
     * Gets the attribute value for CompanyId, using the alias name CompanyId.
     * @return the CompanyId
     */
    public String getCompanyId() {
        return (String)getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyId.
     * @param value value to set the CompanyId
     */
    public void setCompanyId(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for PlanId, using the alias name PlanId.
     * @return the PlanId
     */
    public String getPlanId() {
        return (String)getAttributeInternal(PLANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PlanId.
     * @param value value to set the PlanId
     */
    public void setPlanId(String value) {
        setAttributeInternal(PLANID, value);
    }

    /**
     * Gets the attribute value for ProcessId, using the alias name ProcessId.
     * @return the ProcessId
     */
    public Number getProcessId() {
        return (Number)getAttributeInternal(PROCESSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProcessId.
     * @param value value to set the ProcessId
     */
    public void setProcessId(Number value) {
        setAttributeInternal(PROCESSID, value);
    }

    /**
     * Gets the attribute value for OcId, using the alias name OcId.
     * @return the OcId
     */
    public String getOcId() {
        return (String)getAttributeInternal(OCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OcId.
     * @param value value to set the OcId
     */
    public void setOcId(String value) {
        setAttributeInternal(OCID, value);
    }

    /**
     * Gets the attribute value for TcTopside, using the alias name TcTopside.
     * @return the TcTopside
     */
    public String getTcTopside() {
        return (String)getAttributeInternal(TCTOPSIDE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TcTopside.
     * @param value value to set the TcTopside
     */
    public void setTcTopside(String value) {
        setAttributeInternal(TCTOPSIDE, value);
    }

    /**
     * Gets the attribute value for TcInside, using the alias name TcInside.
     * @return the TcInside
     */
    public String getTcInside() {
        return (String)getAttributeInternal(TCINSIDE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TcInside.
     * @param value value to set the TcInside
     */
    public void setTcInside(String value) {
        setAttributeInternal(TCINSIDE, value);
    }

    /**
     * Gets the attribute value for MachineType, using the alias name MachineType.
     * @return the MachineType
     */
    public String getMachineType() {
        return (String)getAttributeInternal(MACHINETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MachineType.
     * @param value value to set the MachineType
     */
    public void setMachineType(String value) {
        setAttributeInternal(MACHINETYPE, value);
    }

    /**
     * Gets the attribute value for NoOfMachines, using the alias name NoOfMachines.
     * @return the NoOfMachines
     */
    public Number getNoOfMachines() {
        return (Number)getAttributeInternal(NOOFMACHINES);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoOfMachines.
     * @param value value to set the NoOfMachines
     */
    public void setNoOfMachines(Number value) {
        setAttributeInternal(NOOFMACHINES, value);
    }

    /**
     * Gets the attribute value for FootId, using the alias name FootId.
     * @return the FootId
     */
    public String getFootId() {
        return (String)getAttributeInternal(FOOTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FootId.
     * @param value value to set the FootId
     */
    public void setFootId(String value) {
        setAttributeInternal(FOOTID, value);
    }

    /**
     * Gets the attribute value for GuageId, using the alias name GuageId.
     * @return the GuageId
     */
    public String getGuageId() {
        return (String)getAttributeInternal(GUAGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GuageId.
     * @param value value to set the GuageId
     */
    public void setGuageId(String value) {
        setAttributeInternal(GUAGEID, value);
    }

    /**
     * Gets the attribute value for NoOfWp, using the alias name NoOfWp.
     * @return the NoOfWp
     */
    public Number getNoOfWp() {
        return (Number)getAttributeInternal(NOOFWP);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoOfWp.
     * @param value value to set the NoOfWp
     */
    public void setNoOfWp(Number value) {
        setAttributeInternal(NOOFWP, value);
    }

    /**
     * Gets the attribute value for Smv, using the alias name Smv.
     * @return the Smv
     */
    public Number getSmv() {
        return (Number)getAttributeInternal(SMV);
    }

    /**
     * Sets <code>value</code> as the attribute value for Smv.
     * @param value value to set the Smv
     */
    public void setSmv(Number value) {
        setAttributeInternal(SMV, value);
    }

    /**
     * Gets the attribute value for UserId, using the alias name UserId.
     * @return the UserId
     */
    public String getUserId() {
        return (String)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserId.
     * @param value value to set the UserId
     */
    public void setUserId(String value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for UserDate, using the alias name UserDate.
     * @return the UserDate
     */
    public Date getUserDate() {
        return (Date)getAttributeInternal(USERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserDate.
     * @param value value to set the UserDate
     */
    public void setUserDate(Date value) {
        setAttributeInternal(USERDATE, value);
    }

    /**
     * Gets the attribute value for TerminalId, using the alias name TerminalId.
     * @return the TerminalId
     */
    public String getTerminalId() {
        return (String)getAttributeInternal(TERMINALID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TerminalId.
     * @param value value to set the TerminalId
     */
    public void setTerminalId(String value) {
        setAttributeInternal(TERMINALID, value);
    }

    /**
     * Gets the attribute value for LineNum, using the alias name LineNum.
     * @return the LineNum
     */
    public Number getLineNum() {
        return (Number)getAttributeInternal(LINENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineNum.
     * @param value value to set the LineNum
     */
    public void setLineNum(Number value) {
        setAttributeInternal(LINENUM, value);
    }

    /**
     * Gets the attribute value for Target, using the alias name Target.
     * @return the Target
     */
    public String getTarget() {
        return (String)getAttributeInternal(TARGET);
    }

    /**
     * Sets <code>value</code> as the attribute value for Target.
     * @param value value to set the Target
     */
    public void setTarget(String value) {
        setAttributeInternal(TARGET, value);
    }

    /**
     * Gets the attribute value for Points, using the alias name Points.
     * @return the Points
     */
    public Number getPoints() {
        return (Number)getAttributeInternal(POINTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Points.
     * @param value value to set the Points
     */
    public void setPoints(Number value) {
        setAttributeInternal(POINTS, value);
    }

    /**
     * Gets the attribute value for NdlTime, using the alias name NdlTime.
     * @return the NdlTime
     */
    public Number getNdlTime() {
        return (Number)getAttributeInternal(NDLTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for NdlTime.
     * @param value value to set the NdlTime
     */
    public void setNdlTime(Number value) {
        setAttributeInternal(NDLTIME, value);
    }

    /**
     * Gets the attribute value for TotTime, using the alias name TotTime.
     * @return the TotTime
     */
    public Number getTotTime() {
        return (Number)getAttributeInternal(TOTTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotTime.
     * @param value value to set the TotTime
     */
    public void setTotTime(Number value) {
        setAttributeInternal(TOTTIME, value);
    }

    /**
     * Gets the attribute value for SpInst, using the alias name SpInst.
     * @return the SpInst
     */
    public String getSpInst() {
        return (String)getAttributeInternal(SPINST);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpInst.
     * @param value value to set the SpInst
     */
    public void setSpInst(String value) {
        setAttributeInternal(SPINST, value);
    }

    /**
     * Gets the attribute value for ResourceId, using the alias name ResourceId.
     * @return the ResourceId
     */
    public String getResourceId() {
        return (String)getAttributeInternal(RESOURCEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResourceId.
     * @param value value to set the ResourceId
     */
    public void setResourceId(String value) {
        setAttributeInternal(RESOURCEID, value);
    }

    /**
     * Gets the attribute value for PMachineType, using the alias name PMachineType.
     * @return the PMachineType
     */
    public String getPMachineType() {
        return (String)getAttributeInternal(PMACHINETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PMachineType.
     * @param value value to set the PMachineType
     */
    public void setPMachineType(String value) {
        setAttributeInternal(PMACHINETYPE, value);
    }

    /**
     * Gets the attribute value for ResourceVal, using the alias name ResourceVal.
     * @return the ResourceVal
     */
    public Number getResourceVal() {
        return (Number)getAttributeInternal(RESOURCEVAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResourceVal.
     * @param value value to set the ResourceVal
     */
    public void setResourceVal(Number value) {
        setAttributeInternal(RESOURCEVAL, value);
    }

    /**
     * Gets the attribute value for ResourceId2, using the alias name ResourceId2.
     * @return the ResourceId2
     */
    public String getResourceId2() {
        return (String)getAttributeInternal(RESOURCEID2);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResourceId2.
     * @param value value to set the ResourceId2
     */
    public void setResourceId2(String value) {
        setAttributeInternal(RESOURCEID2, value);
    }

    /**
     * Gets the attribute value for ResourceVal2, using the alias name ResourceVal2.
     * @return the ResourceVal2
     */
    public Number getResourceVal2() {
        return (Number)getAttributeInternal(RESOURCEVAL2);
    }

    /**
     * Sets <code>value</code> as the attribute value for ResourceVal2.
     * @param value value to set the ResourceVal2
     */
    public void setResourceVal2(Number value) {
        setAttributeInternal(RESOURCEVAL2, value);
    }

    /**
     * Gets the attribute value for Dposted, using the alias name Dposted.
     * @return the Dposted
     */
    public String getDposted() {
        return (String)getAttributeInternal(DPOSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dposted.
     * @param value value to set the Dposted
     */
    public void setDposted(String value) {
        setAttributeInternal(DPOSTED, value);
    }

    /**
     * Gets the attribute value for TrgtGwp, using the alias name TrgtGwp.
     * @return the TrgtGwp
     */
    public Number getTrgtGwp() {
        return (Number)getAttributeInternal(TRGTGWP);
    }

    /**
     * Sets <code>value</code> as the attribute value for TrgtGwp.
     * @param value value to set the TrgtGwp
     */
    public void setTrgtGwp(Number value) {
        setAttributeInternal(TRGTGWP, value);
    }

    /**
     * Gets the attribute value for CmtQty, using the alias name CmtQty.
     * @return the CmtQty
     */
    public Number getCmtQty() {
        return (Number)getAttributeInternal(CMTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CmtQty.
     * @param value value to set the CmtQty
     */
    public void setCmtQty(Number value) {
        setAttributeInternal(CMTQTY, value);
    }

    /**
     * Gets the attribute value for CmtJobrate, using the alias name CmtJobrate.
     * @return the CmtJobrate
     */
    public Number getCmtJobrate() {
        return (Number)getAttributeInternal(CMTJOBRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CmtJobrate.
     * @param value value to set the CmtJobrate
     */
    public void setCmtJobrate(Number value) {
        setAttributeInternal(CMTJOBRATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for OcType, using the alias name OcType.
     * @return the OcType
     */
    public String getOcType() {
        return (String)getAttributeInternal(OCTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OcType.
     * @param value value to set the OcType
     */
    public void setOcType(String value) {
        setAttributeInternal(OCTYPE, value);
    }

    /**
     * Gets the attribute value for MenPower, using the alias name MenPower.
     * @return the MenPower
     */
    public Number getMenPower() {
        return (Number)getAttributeInternal(MENPOWER);
    }

    /**
     * Sets <code>value</code> as the attribute value for MenPower.
     * @param value value to set the MenPower
     */
    public void setMenPower(Number value) {
        setAttributeInternal(MENPOWER, value);
    }

    /**
     * Gets the attribute value for WorkerType, using the alias name WorkerType.
     * @return the WorkerType
     */
    public String getWorkerType() {
        return (String)getAttributeInternal(WORKERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkerType.
     * @param value value to set the WorkerType
     */
    public void setWorkerType(String value) {
        setAttributeInternal(WORKERTYPE, value);
    }

    /**
     * Gets the attribute value for SqNum, using the alias name SqNum.
     * @return the SqNum
     */
    public Number getSqNum() {
        return (Number)getAttributeInternal(SQNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for SqNum.
     * @param value value to set the SqNum
     */
    public void setSqNum(Number value) {
        setAttributeInternal(SQNUM, value);
    }

    /**
     * Gets the attribute value for ParentOprId, using the alias name ParentOprId.
     * @return the ParentOprId
     */
    public Number getParentOprId() {
        return (Number)getAttributeInternal(PARENTOPRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentOprId.
     * @param value value to set the ParentOprId
     */
    public void setParentOprId(Number value) {
        setAttributeInternal(PARENTOPRID, value);
    }

    /**
     * Gets the attribute value for OcErpCode, using the alias name OcErpCode.
     * @return the OcErpCode
     */
    public String getOcErpCode() {
        return (String)getAttributeInternal(OCERPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OcErpCode.
     * @param value value to set the OcErpCode
     */
    public void setOcErpCode(String value) {
        setAttributeInternal(OCERPCODE, value);
    }

    /**
     * Gets the attribute value for ComponentId, using the alias name ComponentId.
     * @return the ComponentId
     */
    public Number getComponentId() {
        return (Number)getAttributeInternal(COMPONENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ComponentId.
     * @param value value to set the ComponentId
     */
    public void setComponentId(Number value) {
        setAttributeInternal(COMPONENTID, value);
    }

    /**
     * Gets the attribute value for StandardOperationCode, using the alias name StandardOperationCode.
     * @return the StandardOperationCode
     */
    public String getStandardOperationCode() {
        return (String)getAttributeInternal(STANDARDOPERATIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StandardOperationCode.
     * @param value value to set the StandardOperationCode
     */
    public void setStandardOperationCode(String value) {
        setAttributeInternal(STANDARDOPERATIONCODE, value);
    }

    /**
     * Gets the attribute value for ProcessFlow, using the alias name ProcessFlow.
     * @return the ProcessFlow
     */
    public String getProcessFlow() {
        return (String)getAttributeInternal(PROCESSFLOW);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProcessFlow.
     * @param value value to set the ProcessFlow
     */
    public void setProcessFlow(String value) {
        setAttributeInternal(PROCESSFLOW, value);
    }

    /**
     * Gets the attribute value for HelperSmv, using the alias name HelperSmv.
     * @return the HelperSmv
     */
    public Number getHelperSmv() {
        return (Number)getAttributeInternal(HELPERSMV);
    }

    /**
     * Sets <code>value</code> as the attribute value for HelperSmv.
     * @param value value to set the HelperSmv
     */
    public void setHelperSmv(Number value) {
        setAttributeInternal(HELPERSMV, value);
    }

    /**
     * Gets the attribute value for OperatOblineId, using the alias name OperatOblineId.
     * @return the OperatOblineId
     */
    public Number getOperatOblineId() {
        return (Number)getAttributeInternal(OPERATOBLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatOblineId.
     * @param value value to set the OperatOblineId
     */
    public void setOperatOblineId(Number value) {
        setAttributeInternal(OPERATOBLINEID, value);
    }

    /**
     * Gets the attribute value for EmbNoStitch, using the alias name EmbNoStitch.
     * @return the EmbNoStitch
     */
    public Number getEmbNoStitch() {
        return (Number)getAttributeInternal(EMBNOSTITCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmbNoStitch.
     * @param value value to set the EmbNoStitch
     */
    public void setEmbNoStitch(Number value) {
        setAttributeInternal(EMBNOSTITCH, value);
    }

    /**
     * Gets the attribute value for SNo, using the alias name SNo.
     * @return the SNo
     */
    public Number getSNo() {
        return (Number)getAttributeInternal(SNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SNo.
     * @param value value to set the SNo
     */
    public void setSNo(Number value) {
        setAttributeInternal(SNO, value);
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for OpLineId, using the alias name OpLineId.
     * @return the OpLineId
     */
    public Number getOpLineId() {
        return (Number)getAttributeInternal(OPLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpLineId.
     * @param value value to set the OpLineId
     */
    public void setOpLineId(Number value) {
        setAttributeInternal(OPLINEID, value);
    }

    /**
     * Gets the attribute value for ObLinesId, using the alias name ObLinesId.
     * @return the ObLinesId
     */
    public Number getObLinesId() {
        return (Number)getAttributeInternal(OBLINESID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ObLinesId.
     * @param value value to set the ObLinesId
     */
    public void setObLinesId(Number value) {
        setAttributeInternal(OBLINESID, value);
    }

    /**
     * Gets the attribute value for GwpGeObid, using the alias name GwpGeObid.
     * @return the GwpGeObid
     */
    public Number getGwpGeObid() {
        return (Number)getAttributeInternal(GWPGEOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GwpGeObid.
     * @param value value to set the GwpGeObid
     */
    public void setGwpGeObid(Number value) {
        setAttributeInternal(GWPGEOBID, value);
    }

    /**
     * Gets the attribute value for MinorOperations, using the alias name MinorOperations.
     * @return the MinorOperations
     */
    public String getMinorOperations() {
        return (String)getAttributeInternal(MINOROPERATIONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MinorOperations.
     * @param value value to set the MinorOperations
     */
    public void setMinorOperations(String value) {
        setAttributeInternal(MINOROPERATIONS, value);
    }

    /**
     * Gets the attribute value for MajorOperations, using the alias name MajorOperations.
     * @return the MajorOperations
     */
    public String getMajorOperations() {
        return (String)getAttributeInternal(MAJOROPERATIONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MajorOperations.
     * @param value value to set the MajorOperations
     */
    public void setMajorOperations(String value) {
        setAttributeInternal(MAJOROPERATIONS, value);
    }

    /**
     * Gets the attribute value for Water, using the alias name Water.
     * @return the Water
     */
    public String getWater() {
        return (String)getAttributeInternal(WATER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Water.
     * @param value value to set the Water
     */
    public void setWater(String value) {
        setAttributeInternal(WATER, value);
    }

    /**
     * Gets the attribute value for Time, using the alias name Time.
     * @return the Time
     */
    public String getTime() {
        return (String)getAttributeInternal(TIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Time.
     * @param value value to set the Time
     */
    public void setTime(String value) {
        setAttributeInternal(TIME, value);
    }

    /**
     * Gets the attribute value for Sequence, using the alias name Sequence.
     * @return the Sequence
     */
    public String getSequence() {
        return (String)getAttributeInternal(SEQUENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sequence.
     * @param value value to set the Sequence
     */
    public void setSequence(String value) {
        setAttributeInternal(SEQUENCE, value);
    }

    /**
     * Gets the attribute value for WashType, using the alias name WashType.
     * @return the WashType
     */
    public String getWashType() {
        return (String)getAttributeInternal(WASHTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashType.
     * @param value value to set the WashType
     */
    public void setWashType(String value) {
        setAttributeInternal(WASHTYPE, value);
    }

    /**
     * Gets the attribute value for Seq, using the alias name Seq.
     * @return the Seq
     */
    public Number getSeq() {
        return (Number)getAttributeInternal(SEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Seq.
     * @param value value to set the Seq
     */
    public void setSeq(Number value) {
        setAttributeInternal(SEQ, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getChemiRecipiDetailEo() {
        return (RowIterator)getAttributeInternal(CHEMIRECIPIDETAILEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSubProcessEO() {
        return (RowIterator)getAttributeInternal(SUBPROCESSEO);
    }

    /**
     * @return the associated entity HederEOImpl.
     */
    public HederEOImpl getHederEO() {
        return (HederEOImpl)getAttributeInternal(HEDEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity HederEOImpl.
     */
    public void setHederEO(HederEOImpl value) {
        setAttributeInternal(HEDEREO, value);
    }


    /**
     * @param opLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number opLineId) {
        return new Key(new Object[]{opLineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("MNJ_MFG_ROUTING_PLAN_DET_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setOpLineId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

     /**
         * Custom DML update/insert/delete logic here.
         * @param operation the operation type
         * @param e the transaction event
         */
        protected void doDML(int operation, TransactionEvent e) {
            Map sessionScope = ADFContext.getCurrent().getSessionScope();   
            String user = (String)sessionScope.get("userId");
            String orgId  =(String)sessionScope.get("orgId");
            String unitName  =(String)sessionScope.get("unitName");
            
            System.out.println("ASSES INS DO DML 1 ------------------>"+user);
            System.out.println("ASSES INS DO DML 2------------------>"+orgId);
            System.out.println("ASSES INS DML 3 ------------------>"+unitName);
            
            if(DML_UPDATE == operation){
                      try {
                          
                          setLastUpdateDate((Date)Date.getCurrentDate()); 
                          setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                      } catch (SQLException f) {
                          System.out.println(f.getMessage());
                      }
                  }
                  else if (DML_INSERT == operation){
                   
                      try {
                          
                          //setHeaderNo(getSrNoString());
                          //setOrgId(new oracle.jbo.domain.Number(orgId));
                          //setAttribute1(unitName);
                          setCreationDate((Date)Date.getCurrentDate());  
                          setCreatedBy(new oracle.jbo.domain.Number(user));
                         
                         
                         
                      } catch (SQLException f) {
                          ;
                      }
                  } 
            
            super.doDML(operation, e);
        }

}
