package mnj.mfg.model.entities;

import java.sql.SQLException;

import java.util.Map;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 05 16:57:25 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HederEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        GwpGeId {
            public Object get(HederEOImpl obj) {
                return obj.getGwpGeId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setGwpGeId((Number)value);
            }
        }
        ,
        GwpGeNumber {
            public Object get(HederEOImpl obj) {
                return obj.getGwpGeNumber();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setGwpGeNumber((Number)value);
            }
        }
        ,
        GeDate {
            public Object get(HederEOImpl obj) {
                return obj.getGeDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setGeDate((Date)value);
            }
        }
        ,
        SalesorderId {
            public Object get(HederEOImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSalesorderId((String)value);
            }
        }
        ,
        DoubleWash {
            public Object get(HederEOImpl obj) {
                return obj.getDoubleWash();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setDoubleWash((String)value);
            }
        }
        ,
        AvgGarmentDay {
            public Object get(HederEOImpl obj) {
                return obj.getAvgGarmentDay();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAvgGarmentDay((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(HederEOImpl obj) {
                return obj.getRemarks();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(HederEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(HederEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(HederEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(HederEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        GeStatus {
            public Object get(HederEOImpl obj) {
                return obj.getGeStatus();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setGeStatus((String)value);
            }
        }
        ,
        SoHeaderId {
            public Object get(HederEOImpl obj) {
                return obj.getSoHeaderId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSoHeaderId((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(HederEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        CustomerId {
            public Object get(HederEOImpl obj) {
                return obj.getCustomerId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCustomerId((Number)value);
            }
        }
        ,
        Quantity {
            public Object get(HederEOImpl obj) {
                return obj.getQuantity();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        Brand {
            public Object get(HederEOImpl obj) {
                return obj.getBrand();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setBrand((String)value);
            }
        }
        ,
        Season {
            public Object get(HederEOImpl obj) {
                return obj.getSeason();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        Division {
            public Object get(HederEOImpl obj) {
                return obj.getDivision();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setDivision((String)value);
            }
        }
        ,
        Osp {
            public Object get(HederEOImpl obj) {
                return obj.getOsp();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setOsp((String)value);
            }
        }
        ,
        Style {
            public Object get(HederEOImpl obj) {
                return obj.getStyle();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Wash {
            public Object get(HederEOImpl obj) {
                return obj.getWash();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setWash((String)value);
            }
        }
        ,
        VersionNo {
            public Object get(HederEOImpl obj) {
                return obj.getVersionNo();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setVersionNo((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(HederEOImpl obj) {
                return obj.getVersionDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        Color {
            public Object get(HederEOImpl obj) {
                return obj.getColor();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        TransactionDate {
            public Object get(HederEOImpl obj) {
                return obj.getTransactionDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setTransactionDate((Date)value);
            }
        }
        ,
        WashCatagory {
            public Object get(HederEOImpl obj) {
                return obj.getWashCatagory();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setWashCatagory((String)value);
            }
        }
        ,
        SystemId {
            public Object get(HederEOImpl obj) {
                return obj.getSystemId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        LineEOStyleDetail {
            public Object get(HederEOImpl obj) {
                return obj.getLineEOStyleDetail();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        DetailRecipesEO {
            public Object get(HederEOImpl obj) {
                return obj.getDetailRecipesEO();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(HederEOImpl object);

        public abstract void put(HederEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GWPGEID = AttributesEnum.GwpGeId.index();
    public static final int GWPGENUMBER = AttributesEnum.GwpGeNumber.index();
    public static final int GEDATE = AttributesEnum.GeDate.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int DOUBLEWASH = AttributesEnum.DoubleWash.index();
    public static final int AVGGARMENTDAY = AttributesEnum.AvgGarmentDay.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int GESTATUS = AttributesEnum.GeStatus.index();
    public static final int SOHEADERID = AttributesEnum.SoHeaderId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int BRAND = AttributesEnum.Brand.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int DIVISION = AttributesEnum.Division.index();
    public static final int OSP = AttributesEnum.Osp.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int WASH = AttributesEnum.Wash.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int TRANSACTIONDATE = AttributesEnum.TransactionDate.index();
    public static final int WASHCATAGORY = AttributesEnum.WashCatagory.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int LINEEOSTYLEDETAIL = AttributesEnum.LineEOStyleDetail.index();
    public static final int DETAILRECIPESEO = AttributesEnum.DetailRecipesEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HederEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.HederEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for GwpGeId, using the alias name GwpGeId.
     * @return the GwpGeId
     */
    public Number getGwpGeId() {
        return (Number)getAttributeInternal(GWPGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GwpGeId.
     * @param value value to set the GwpGeId
     */
    public void setGwpGeId(Number value) {
        setAttributeInternal(GWPGEID, value);
    }

    /**
     * Gets the attribute value for GwpGeNumber, using the alias name GwpGeNumber.
     * @return the GwpGeNumber
     */
    public Number getGwpGeNumber() {
        return (Number)getAttributeInternal(GWPGENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for GwpGeNumber.
     * @param value value to set the GwpGeNumber
     */
    public void setGwpGeNumber(Number value) {
        setAttributeInternal(GWPGENUMBER, value);
    }

    /**
     * Gets the attribute value for GeDate, using the alias name GeDate.
     * @return the GeDate
     */
    public Date getGeDate() {
        return (Date)getAttributeInternal(GEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GeDate.
     * @param value value to set the GeDate
     */
    public void setGeDate(Date value) {
        setAttributeInternal(GEDATE, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public String getSalesorderId() {
        return (String)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(String value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for DoubleWash, using the alias name DoubleWash.
     * @return the DoubleWash
     */
    public String getDoubleWash() {
        return (String)getAttributeInternal(DOUBLEWASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for DoubleWash.
     * @param value value to set the DoubleWash
     */
    public void setDoubleWash(String value) {
        setAttributeInternal(DOUBLEWASH, value);
    }

    /**
     * Gets the attribute value for AvgGarmentDay, using the alias name AvgGarmentDay.
     * @return the AvgGarmentDay
     */
    public Number getAvgGarmentDay() {
        return (Number)getAttributeInternal(AVGGARMENTDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AvgGarmentDay.
     * @param value value to set the AvgGarmentDay
     */
    public void setAvgGarmentDay(Number value) {
        setAttributeInternal(AVGGARMENTDAY, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for GeStatus, using the alias name GeStatus.
     * @return the GeStatus
     */
    public String getGeStatus() {
        return (String)getAttributeInternal(GESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for GeStatus.
     * @param value value to set the GeStatus
     */
    public void setGeStatus(String value) {
        setAttributeInternal(GESTATUS, value);
    }

    /**
     * Gets the attribute value for SoHeaderId, using the alias name SoHeaderId.
     * @return the SoHeaderId
     */
    public Number getSoHeaderId() {
        return (Number)getAttributeInternal(SOHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoHeaderId.
     * @param value value to set the SoHeaderId
     */
    public void setSoHeaderId(Number value) {
        setAttributeInternal(SOHEADERID, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for CustomerId, using the alias name CustomerId.
     * @return the CustomerId
     */
    public Number getCustomerId() {
        return (Number)getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerId.
     * @param value value to set the CustomerId
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the Quantity
     */
    public Number getQuantity() {
        return (Number)getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for Brand, using the alias name Brand.
     * @return the Brand
     */
    public String getBrand() {
        return (String)getAttributeInternal(BRAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for Brand.
     * @param value value to set the Brand
     */
    public void setBrand(String value) {
        setAttributeInternal(BRAND, value);
    }

    /**
     * Gets the attribute value for Season, using the alias name Season.
     * @return the Season
     */
    public String getSeason() {
        return (String)getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for Season.
     * @param value value to set the Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for Division, using the alias name Division.
     * @return the Division
     */
    public String getDivision() {
        return (String)getAttributeInternal(DIVISION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Division.
     * @param value value to set the Division
     */
    public void setDivision(String value) {
        setAttributeInternal(DIVISION, value);
    }

    /**
     * Gets the attribute value for Osp, using the alias name Osp.
     * @return the Osp
     */
    public String getOsp() {
        return (String)getAttributeInternal(OSP);
    }

    /**
     * Sets <code>value</code> as the attribute value for Osp.
     * @param value value to set the Osp
     */
    public void setOsp(String value) {
        setAttributeInternal(OSP, value);
    }

    /**
     * Gets the attribute value for Style, using the alias name Style.
     * @return the Style
     */
    public String getStyle() {
        return (String)getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Style.
     * @param value value to set the Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for Wash, using the alias name Wash.
     * @return the Wash
     */
    public String getWash() {
        return (String)getAttributeInternal(WASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Wash.
     * @param value value to set the Wash
     */
    public void setWash(String value) {
        setAttributeInternal(WASH, value);
    }

    /**
     * Gets the attribute value for VersionNo, using the alias name VersionNo.
     * @return the VersionNo
     */
    public Number getVersionNo() {
        return (Number)getAttributeInternal(VERSIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNo.
     * @param value value to set the VersionNo
     */
    public void setVersionNo(Number value) {
        setAttributeInternal(VERSIONNO, value);
    }

    /**
     * Gets the attribute value for VersionDate, using the alias name VersionDate.
     * @return the VersionDate
     */
    public Date getVersionDate() {
        return (Date)getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionDate.
     * @param value value to set the VersionDate
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for Color, using the alias name Color.
     * @return the Color
     */
    public String getColor() {
        return (String)getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Color.
     * @param value value to set the Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for TransactionDate, using the alias name TransactionDate.
     * @return the TransactionDate
     */
    public Date getTransactionDate() {
        return (Date)getAttributeInternal(TRANSACTIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionDate.
     * @param value value to set the TransactionDate
     */
    public void setTransactionDate(Date value) {
        setAttributeInternal(TRANSACTIONDATE, value);
    }

    /**
     * Gets the attribute value for WashCatagory, using the alias name WashCatagory.
     * @return the WashCatagory
     */
    public String getWashCatagory() {
        return (String)getAttributeInternal(WASHCATAGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashCatagory.
     * @param value value to set the WashCatagory
     */
    public void setWashCatagory(String value) {
        setAttributeInternal(WASHCATAGORY, value);
    }

    /**
     * Gets the attribute value for SystemId, using the alias name SystemId.
     * @return the SystemId
     */
    public Number getSystemId() {
        return (Number)getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SystemId.
     * @param value value to set the SystemId
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getLineEOStyleDetail() {
        return (RowIterator)getAttributeInternal(LINEEOSTYLEDETAIL);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getDetailRecipesEO() {
        return (RowIterator)getAttributeInternal(DETAILRECIPESEO);
    }


    /**
     * @param gwpGeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number gwpGeId) {
        return new Key(new Object[]{gwpGeId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("MNJ_GWP_MFG_GEVALUATION_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setGwpGeId(sVal);
        //setGwpGeNumber(new oracle.jbo.domain.Number(getSrNoString()));
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {

        //super.doDML(operation, e);
        System.out.println("In doDML");

        Map sessionScope = ADFContext.getCurrent().getSessionScope();

        String user = (String)sessionScope.get("userId");
        String orgId = (String)sessionScope.get("orgId");
        String unitName = (String)sessionScope.get("unitName");

        System.out.println("Session Parameters are... " + user + " " + orgId +
                           " " + unitName);

        if (operation == DML_INSERT) {
            System.out.println("In Insert");
            try {
                setOrgId(new oracle.jbo.domain.Number(orgId));
                setDivision(unitName);
              //  checkduplication();
                setGwpGeNumber(new oracle.jbo.domain.Number(getSrNoString()));
                System.out.println("Document No -->" + getSrNoString());
                setCreationDate((Date)Date.getCurrentDate());
                setCreatedBy(new oracle.jbo.domain.Number(user));
            } catch (SQLException f) {
                ;
            }
        } else if (DML_UPDATE == operation) {
            System.out.println("In Update");
            try {
                setLastUpdateDate((Date)Date.getCurrentDate());
                setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                //checkduplication();
            } catch (SQLException f) {
                ;
            }
        }

       super.doDML(operation, e);

    }

    public int getSrNoString() {
        int srno = 0;
        String stmt = "BEGIN :1 := cust_mnj_mfg_pkg.ge_srno; end;";
        java.sql.CallableStatement cs =
            getDBTransaction().createCallableStatement(stmt, 1);
        try {
            cs.registerOutParameter(1, oracle.jdbc.OracleTypes.VARCHAR);
            cs.execute();
            srno = cs.getInt(1);
            cs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return srno;
    }

    public void checkduplication() {
        ViewObject voFmn1 =
            getDBTransaction().createViewObjectFromQueryStmt("select count(*) from MNJ_GWP_MFG_GEVALUATION h\n" +
                "where h.customer_id = '" + getCustomerId() +
                "' and h.org_id = '" + getOrgId() + "'\n" +
                "and h.style = '" + getStyle() + "' and h.season = '" +
                getSeason() + "'\n" +
                "and h.wash = '" + getWash() + "' and h.color = '" +
                getColor() + "' and h.GWP_GE_ID != '" + getGwpGeId() + "'");
        voFmn1.executeQuery();
        voFmn1.first();
        System.out.println("Query is.... ---> " + voFmn1.getQuery());
        if (Integer.parseInt(voFmn1.getCurrentRow().getAttribute(0).toString()) >=
            1)

        {
            FacesContext context = FacesContext.getCurrentInstance();
            FacesMessage message =
                new FacesMessage(FacesMessage.SEVERITY_ERROR,
                                 "Duplicate Record Found...", "");
            context.addMessage(null, message);
        }

        else {
            FacesContext context = FacesContext.getCurrentInstance();
            FacesMessage message = new FacesMessage("Record Saved...");
            context.addMessage(null, message);
        }

    }

}
