package mnj.mfg.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 05 17:15:19 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LineEOStyleDetailImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        GwpGeId {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getGwpGeId();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setGwpGeId((Number)value);
            }
        }
        ,
        GwpGeWaslineId {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getGwpGeWaslineId();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setGwpGeWaslineId((Number)value);
            }
        }
        ,
        GwpGeObid {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getGwpGeObid();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setGwpGeObid((Number)value);
            }
        }
        ,
        Salesorder {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getSalesorder();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setSalesorder((Number)value);
            }
        }
        ,
        SoLine {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getSoLine();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setSoLine((Number)value);
            }
        }
        ,
        GwpUnitId {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getGwpUnitId();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setGwpUnitId((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getCreationDate();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        ObsNo {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getObsNo();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setObsNo((String)value);
            }
        }
        ,
        Quantity {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getQuantity();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        PostStatus {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getPostStatus();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setPostStatus((String)value);
            }
        }
        ,
        JobStatus {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getJobStatus();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setJobStatus((String)value);
            }
        }
        ,
        WipEntityId {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getWipEntityId();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setWipEntityId((Number)value);
            }
        }
        ,
        JobReleasedDate {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getJobReleasedDate();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setJobReleasedDate((Date)value);
            }
        }
        ,
        WashName {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getWashName();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setWashName((String)value);
            }
        }
        ,
        WashingUnitName {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getWashingUnitName();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setWashingUnitName((String)value);
            }
        }
        ,
        WashingStartDate {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getWashingStartDate();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setWashingStartDate((Date)value);
            }
        }
        ,
        StitchingUnit {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getStitchingUnit();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setStitchingUnit((String)value);
            }
        }
        ,
        StitchingStartDate {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getStitchingStartDate();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setStitchingStartDate((Date)value);
            }
        }
        ,
        ViewShipmentDetail {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getViewShipmentDetail();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setViewShipmentDetail((String)value);
            }
        }
        ,
        TemCode {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getTemCode();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setTemCode((String)value);
            }
        }
        ,
        ShipmentQty {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getShipmentQty();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setShipmentQty((Number)value);
            }
        }
        ,
        ShipmentDate {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getShipmentDate();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setShipmentDate((Date)value);
            }
        }
        ,
        CountryChange {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getCountryChange();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setCountryChange((String)value);
            }
        }
        ,
        ItemId {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getItemId();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        CurrentPlanQty {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getCurrentPlanQty();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setCurrentPlanQty((Number)value);
            }
        }
        ,
        BalanceQty {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getBalanceQty();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setBalanceQty((Number)value);
            }
        }
        ,
        BpoId {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getBpoId();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setBpoId((Number)value);
            }
        }
        ,
        HederEO {
            public Object get(LineEOStyleDetailImpl obj) {
                return obj.getHederEO();
            }

            public void put(LineEOStyleDetailImpl obj, Object value) {
                obj.setHederEO((HederEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(LineEOStyleDetailImpl object);

        public abstract void put(LineEOStyleDetailImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GWPGEID = AttributesEnum.GwpGeId.index();
    public static final int GWPGEWASLINEID = AttributesEnum.GwpGeWaslineId.index();
    public static final int GWPGEOBID = AttributesEnum.GwpGeObid.index();
    public static final int SALESORDER = AttributesEnum.Salesorder.index();
    public static final int SOLINE = AttributesEnum.SoLine.index();
    public static final int GWPUNITID = AttributesEnum.GwpUnitId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int OBSNO = AttributesEnum.ObsNo.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int POSTSTATUS = AttributesEnum.PostStatus.index();
    public static final int JOBSTATUS = AttributesEnum.JobStatus.index();
    public static final int WIPENTITYID = AttributesEnum.WipEntityId.index();
    public static final int JOBRELEASEDDATE = AttributesEnum.JobReleasedDate.index();
    public static final int WASHNAME = AttributesEnum.WashName.index();
    public static final int WASHINGUNITNAME = AttributesEnum.WashingUnitName.index();
    public static final int WASHINGSTARTDATE = AttributesEnum.WashingStartDate.index();
    public static final int STITCHINGUNIT = AttributesEnum.StitchingUnit.index();
    public static final int STITCHINGSTARTDATE = AttributesEnum.StitchingStartDate.index();
    public static final int VIEWSHIPMENTDETAIL = AttributesEnum.ViewShipmentDetail.index();
    public static final int TEMCODE = AttributesEnum.TemCode.index();
    public static final int SHIPMENTQTY = AttributesEnum.ShipmentQty.index();
    public static final int SHIPMENTDATE = AttributesEnum.ShipmentDate.index();
    public static final int COUNTRYCHANGE = AttributesEnum.CountryChange.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int CURRENTPLANQTY = AttributesEnum.CurrentPlanQty.index();
    public static final int BALANCEQTY = AttributesEnum.BalanceQty.index();
    public static final int BPOID = AttributesEnum.BpoId.index();
    public static final int HEDEREO = AttributesEnum.HederEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LineEOStyleDetailImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.LineEOStyleDetail");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for GwpGeId, using the alias name GwpGeId.
     * @return the GwpGeId
     */
    public Number getGwpGeId() {
        return (Number)getAttributeInternal(GWPGEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GwpGeId.
     * @param value value to set the GwpGeId
     */
    public void setGwpGeId(Number value) {
        setAttributeInternal(GWPGEID, value);
    }

    /**
     * Gets the attribute value for GwpGeWaslineId, using the alias name GwpGeWaslineId.
     * @return the GwpGeWaslineId
     */
    public Number getGwpGeWaslineId() {
        return (Number)getAttributeInternal(GWPGEWASLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GwpGeWaslineId.
     * @param value value to set the GwpGeWaslineId
     */
    public void setGwpGeWaslineId(Number value) {
        setAttributeInternal(GWPGEWASLINEID, value);
    }

    /**
     * Gets the attribute value for GwpGeObid, using the alias name GwpGeObid.
     * @return the GwpGeObid
     */
    public Number getGwpGeObid() {
        return (Number)getAttributeInternal(GWPGEOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GwpGeObid.
     * @param value value to set the GwpGeObid
     */
    public void setGwpGeObid(Number value) {
        setAttributeInternal(GWPGEOBID, value);
    }

    /**
     * Gets the attribute value for Salesorder, using the alias name Salesorder.
     * @return the Salesorder
     */
    public Number getSalesorder() {
        return (Number)getAttributeInternal(SALESORDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salesorder.
     * @param value value to set the Salesorder
     */
    public void setSalesorder(Number value) {
        setAttributeInternal(SALESORDER, value);
    }

    /**
     * Gets the attribute value for SoLine, using the alias name SoLine.
     * @return the SoLine
     */
    public Number getSoLine() {
        return (Number)getAttributeInternal(SOLINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoLine.
     * @param value value to set the SoLine
     */
    public void setSoLine(Number value) {
        setAttributeInternal(SOLINE, value);
    }

    /**
     * Gets the attribute value for GwpUnitId, using the alias name GwpUnitId.
     * @return the GwpUnitId
     */
    public String getGwpUnitId() {
        return (String)getAttributeInternal(GWPUNITID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GwpUnitId.
     * @param value value to set the GwpUnitId
     */
    public void setGwpUnitId(String value) {
        setAttributeInternal(GWPUNITID, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for ObsNo, using the alias name ObsNo.
     * @return the ObsNo
     */
    public String getObsNo() {
        return (String)getAttributeInternal(OBSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ObsNo.
     * @param value value to set the ObsNo
     */
    public void setObsNo(String value) {
        setAttributeInternal(OBSNO, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the Quantity
     */
    public Number getQuantity() {
        return (Number)getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for PostStatus, using the alias name PostStatus.
     * @return the PostStatus
     */
    public String getPostStatus() {
        return (String)getAttributeInternal(POSTSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostStatus.
     * @param value value to set the PostStatus
     */
    public void setPostStatus(String value) {
        setAttributeInternal(POSTSTATUS, value);
    }

    /**
     * Gets the attribute value for JobStatus, using the alias name JobStatus.
     * @return the JobStatus
     */
    public String getJobStatus() {
        return (String)getAttributeInternal(JOBSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobStatus.
     * @param value value to set the JobStatus
     */
    public void setJobStatus(String value) {
        setAttributeInternal(JOBSTATUS, value);
    }

    /**
     * Gets the attribute value for WipEntityId, using the alias name WipEntityId.
     * @return the WipEntityId
     */
    public Number getWipEntityId() {
        return (Number)getAttributeInternal(WIPENTITYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WipEntityId.
     * @param value value to set the WipEntityId
     */
    public void setWipEntityId(Number value) {
        setAttributeInternal(WIPENTITYID, value);
    }

    /**
     * Gets the attribute value for JobReleasedDate, using the alias name JobReleasedDate.
     * @return the JobReleasedDate
     */
    public Date getJobReleasedDate() {
        return (Date)getAttributeInternal(JOBRELEASEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobReleasedDate.
     * @param value value to set the JobReleasedDate
     */
    public void setJobReleasedDate(Date value) {
        setAttributeInternal(JOBRELEASEDDATE, value);
    }

    /**
     * Gets the attribute value for WashName, using the alias name WashName.
     * @return the WashName
     */
    public String getWashName() {
        return (String)getAttributeInternal(WASHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashName.
     * @param value value to set the WashName
     */
    public void setWashName(String value) {
        setAttributeInternal(WASHNAME, value);
    }

    /**
     * Gets the attribute value for WashingUnitName, using the alias name WashingUnitName.
     * @return the WashingUnitName
     */
    public String getWashingUnitName() {
        return (String)getAttributeInternal(WASHINGUNITNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashingUnitName.
     * @param value value to set the WashingUnitName
     */
    public void setWashingUnitName(String value) {
        setAttributeInternal(WASHINGUNITNAME, value);
    }

    /**
     * Gets the attribute value for WashingStartDate, using the alias name WashingStartDate.
     * @return the WashingStartDate
     */
    public Date getWashingStartDate() {
        return (Date)getAttributeInternal(WASHINGSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashingStartDate.
     * @param value value to set the WashingStartDate
     */
    public void setWashingStartDate(Date value) {
        setAttributeInternal(WASHINGSTARTDATE, value);
    }

    /**
     * Gets the attribute value for StitchingUnit, using the alias name StitchingUnit.
     * @return the StitchingUnit
     */
    public String getStitchingUnit() {
        return (String)getAttributeInternal(STITCHINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for StitchingUnit.
     * @param value value to set the StitchingUnit
     */
    public void setStitchingUnit(String value) {
        setAttributeInternal(STITCHINGUNIT, value);
    }

    /**
     * Gets the attribute value for StitchingStartDate, using the alias name StitchingStartDate.
     * @return the StitchingStartDate
     */
    public Date getStitchingStartDate() {
        return (Date)getAttributeInternal(STITCHINGSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StitchingStartDate.
     * @param value value to set the StitchingStartDate
     */
    public void setStitchingStartDate(Date value) {
        setAttributeInternal(STITCHINGSTARTDATE, value);
    }

    /**
     * Gets the attribute value for ViewShipmentDetail, using the alias name ViewShipmentDetail.
     * @return the ViewShipmentDetail
     */
    public String getViewShipmentDetail() {
        return (String)getAttributeInternal(VIEWSHIPMENTDETAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ViewShipmentDetail.
     * @param value value to set the ViewShipmentDetail
     */
    public void setViewShipmentDetail(String value) {
        setAttributeInternal(VIEWSHIPMENTDETAIL, value);
    }

    /**
     * Gets the attribute value for TemCode, using the alias name TemCode.
     * @return the TemCode
     */
    public String getTemCode() {
        return (String)getAttributeInternal(TEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TemCode.
     * @param value value to set the TemCode
     */
    public void setTemCode(String value) {
        setAttributeInternal(TEMCODE, value);
    }

    /**
     * Gets the attribute value for ShipmentQty, using the alias name ShipmentQty.
     * @return the ShipmentQty
     */
    public Number getShipmentQty() {
        return (Number)getAttributeInternal(SHIPMENTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentQty.
     * @param value value to set the ShipmentQty
     */
    public void setShipmentQty(Number value) {
        setAttributeInternal(SHIPMENTQTY, value);
    }

    /**
     * Gets the attribute value for ShipmentDate, using the alias name ShipmentDate.
     * @return the ShipmentDate
     */
    public Date getShipmentDate() {
        return (Date)getAttributeInternal(SHIPMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentDate.
     * @param value value to set the ShipmentDate
     */
    public void setShipmentDate(Date value) {
        setAttributeInternal(SHIPMENTDATE, value);
    }

    /**
     * Gets the attribute value for CountryChange, using the alias name CountryChange.
     * @return the CountryChange
     */
    public String getCountryChange() {
        return (String)getAttributeInternal(COUNTRYCHANGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CountryChange.
     * @param value value to set the CountryChange
     */
    public void setCountryChange(String value) {
        setAttributeInternal(COUNTRYCHANGE, value);
    }

    /**
     * Gets the attribute value for ItemId, using the alias name ItemId.
     * @return the ItemId
     */
    public Number getItemId() {
        return (Number)getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemId.
     * @param value value to set the ItemId
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for CurrentPlanQty, using the alias name CurrentPlanQty.
     * @return the CurrentPlanQty
     */
    public Number getCurrentPlanQty() {
        return (Number)getAttributeInternal(CURRENTPLANQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrentPlanQty.
     * @param value value to set the CurrentPlanQty
     */
    public void setCurrentPlanQty(Number value) {
        setAttributeInternal(CURRENTPLANQTY, value);
    }

    /**
     * Gets the attribute value for BalanceQty, using the alias name BalanceQty.
     * @return the BalanceQty
     */
    public Number getBalanceQty() {
        return (Number)getAttributeInternal(BALANCEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BalanceQty.
     * @param value value to set the BalanceQty
     */
    public void setBalanceQty(Number value) {
        setAttributeInternal(BALANCEQTY, value);
    }

    /**
     * Gets the attribute value for BpoId, using the alias name BpoId.
     * @return the BpoId
     */
    public Number getBpoId() {
        return (Number)getAttributeInternal(BPOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoId.
     * @param value value to set the BpoId
     */
    public void setBpoId(Number value) {
        setAttributeInternal(BPOID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity HederEOImpl.
     */
    public HederEOImpl getHederEO() {
        return (HederEOImpl)getAttributeInternal(HEDEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity HederEOImpl.
     */
    public void setHederEO(HederEOImpl value) {
        setAttributeInternal(HEDEREO, value);
    }


    /**
     * @param gwpGeObid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number gwpGeObid) {
        return new Key(new Object[]{gwpGeObid});
    }

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_GWP_MFG_GE_OBSLINE_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setGwpGeObid(sVal);
    }
    
    /**
        * Custom DML update/insert/delete logic here.
        * @param operation the operation type
        * @param e the transaction event
        */
       protected void doDML(int operation, TransactionEvent e) {
           Map sessionScope = ADFContext.getCurrent().getSessionScope();   
           String user = (String)sessionScope.get("userId");
           String orgId  =(String)sessionScope.get("orgId");
           String unitName  =(String)sessionScope.get("unitName");
           
           System.out.println("ASSES INS DO DML 1 ------------------>"+user);
           System.out.println("ASSES INS DO DML 2------------------>"+orgId);
           System.out.println("ASSES INS DML 3 ------------------>"+unitName);
           
           if(DML_UPDATE == operation){
                     try {
                         
                         setLastUpdateDate((Date)Date.getCurrentDate()); 
                         setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                     } catch (SQLException f) {
                         System.out.println(f.getMessage());
                     }
                 }
                 else if (DML_INSERT == operation){
                  
                     try {
                         
                         //setHeaderNo(getSrNoString());
                         //setOrgId(new oracle.jbo.domain.Number(orgId));
                         //setAttribute1(unitName);
                         setCreationDate((Date)Date.getCurrentDate());  
                         setCreatedBy(new oracle.jbo.domain.Number(user));
                        
                        
                        
                     } catch (SQLException f) {
                         ;
                     }
                 } 
           
           super.doDML(operation, e);
       }



}
