package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 06 19:00:54 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ItemCodeLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ItemCodeLovImpl() {
    }


}
