package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 06 12:03:56 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrderNoLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OrderNoLovImpl() {
    }


    /**
     * Returns the bind variable value for p_ordrno.
     * @return bind variable value for p_ordrno
     */
    public String getp_ordrno() {
        return (String)getNamedWhereClauseParam("p_ordrno");
    }

    /**
     * Sets <code>value</code> for bind variable p_ordrno.
     * @param value value to bind as p_ordrno
     */
    public void setp_ordrno(String value) {
        setNamedWhereClauseParam("p_ordrno", value);
    }

    /**
     * Returns the variable value for p_Quantity.
     * @return variable value for p_Quantity
     */
    public String getp_Quantity() {
        return (String)ensureVariableManager().getVariableValue("p_Quantity");
    }

    /**
     * Sets <code>value</code> for variable p_Quantity.
     * @param value value to bind as p_Quantity
     */
    public void setp_Quantity(String value) {
        ensureVariableManager().setVariableValue("p_Quantity", value);
    }
}
