package mnj.mfg.model.lov.views;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 10 16:03:14 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ShipmentDetilVoRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(ShipmentDetilVoRowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(ShipmentDetilVoRowImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(ShipmentDetilVoRowImpl obj) {
                return obj.getLineId();
            }

            public void put(ShipmentDetilVoRowImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        OrderNumber {
            public Object get(ShipmentDetilVoRowImpl obj) {
                return obj.getOrderNumber();
            }

            public void put(ShipmentDetilVoRowImpl obj, Object value) {
                obj.setOrderNumber((Number)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(ShipmentDetilVoRowImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(ShipmentDetilVoRowImpl obj, Object value) {
                obj.setInventoryItemId((Number)value);
            }
        }
        ,
        ShippedQuantity {
            public Object get(ShipmentDetilVoRowImpl obj) {
                return obj.getShippedQuantity();
            }

            public void put(ShipmentDetilVoRowImpl obj, Object value) {
                obj.setShippedQuantity((Number)value);
            }
        }
        ,
        ScheduleShipDate {
            public Object get(ShipmentDetilVoRowImpl obj) {
                return obj.getScheduleShipDate();
            }

            public void put(ShipmentDetilVoRowImpl obj, Object value) {
                obj.setScheduleShipDate((Date)value);
            }
        }
        ,
        CountryChange {
            public Object get(ShipmentDetilVoRowImpl obj) {
                return obj.getCountryChange();
            }

            public void put(ShipmentDetilVoRowImpl obj, Object value) {
                obj.setCountryChange((String)value);
            }
        }
        ,
        MultiSelect {
            public Object get(ShipmentDetilVoRowImpl obj) {
                return obj.getMultiSelect();
            }

            public void put(ShipmentDetilVoRowImpl obj, Object value) {
                obj.setMultiSelect((Boolean)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ShipmentDetilVoRowImpl object);

        public abstract void put(ShipmentDetilVoRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int ORDERNUMBER = AttributesEnum.OrderNumber.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int SHIPPEDQUANTITY = AttributesEnum.ShippedQuantity.index();
    public static final int SCHEDULESHIPDATE = AttributesEnum.ScheduleShipDate.index();
    public static final int COUNTRYCHANGE = AttributesEnum.CountryChange.index();
    public static final int MULTISELECT = AttributesEnum.MultiSelect.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ShipmentDetilVoRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HeaderId.
     * @param value value to set the  HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LineId.
     * @param value value to set the  LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderNumber.
     * @return the OrderNumber
     */
    public Number getOrderNumber() {
        return (Number) getAttributeInternal(ORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrderNumber.
     * @param value value to set the  OrderNumber
     */
    public void setOrderNumber(Number value) {
        setAttributeInternal(ORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InventoryItemId.
     * @return the InventoryItemId
     */
    public Number getInventoryItemId() {
        return (Number) getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InventoryItemId.
     * @param value value to set the  InventoryItemId
     */
    public void setInventoryItemId(Number value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ShippedQuantity.
     * @return the ShippedQuantity
     */
    public Number getShippedQuantity() {
        return (Number) getAttributeInternal(SHIPPEDQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShippedQuantity.
     * @param value value to set the  ShippedQuantity
     */
    public void setShippedQuantity(Number value) {
        setAttributeInternal(SHIPPEDQUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ScheduleShipDate.
     * @return the ScheduleShipDate
     */
    public Date getScheduleShipDate() {
        return (Date) getAttributeInternal(SCHEDULESHIPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ScheduleShipDate.
     * @param value value to set the  ScheduleShipDate
     */
    public void setScheduleShipDate(Date value) {
        setAttributeInternal(SCHEDULESHIPDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CountryChange.
     * @return the CountryChange
     */
    public String getCountryChange() {
        return (String) getAttributeInternal(COUNTRYCHANGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CountryChange.
     * @param value value to set the  CountryChange
     */
    public void setCountryChange(String value) {
        setAttributeInternal(COUNTRYCHANGE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MultiSelect.
     * @return the MultiSelect
     */
    public Boolean getMultiSelect() {
        return (Boolean) getAttributeInternal(MULTISELECT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MultiSelect.
     * @param value value to set the  MultiSelect
     */
    public void setMultiSelect(Boolean value) {
        setAttributeInternal(MULTISELECT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
