package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 07 16:39:53 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StitchingWAImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StitchingWAImpl() {
    }

    /**
     * Returns the variable value for p_stitching.
     * @return variable value for p_stitching
     */
    public String getp_stitching() {
        return (String)ensureVariableManager().getVariableValue("p_stitching");
    }

    /**
     * Sets <code>value</code> for variable p_stitching.
     * @param value value to bind as p_stitching
     */
    public void setp_stitching(String value) {
        ensureVariableManager().setVariableValue("p_stitching", value);
    }
}
