package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 06 15:33:34 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StnLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StnLOVImpl() {
    }

    /**
     * Returns the bind variable value for p_orderHeaderId.
     * @return bind variable value for p_orderHeaderId
     */
    public String getp_orderHeaderId() {
        return (String)getNamedWhereClauseParam("p_orderHeaderId");
    }

    /**
     * Sets <code>value</code> for bind variable p_orderHeaderId.
     * @param value value to bind as p_orderHeaderId
     */
    public void setp_orderHeaderId(String value) {
        setNamedWhereClauseParam("p_orderHeaderId", value);
    }

    /**
     * Returns the variable value for p_stn.
     * @return variable value for p_stn
     */
    public String getp_stn() {
        return (String)ensureVariableManager().getVariableValue("p_stn");
    }

    /**
     * Sets <code>value</code> for variable p_stn.
     * @param value value to bind as p_stn
     */
    public void setp_stn(String value) {
        ensureVariableManager().setVariableValue("p_stn", value);
    }
}
