package mnj.mfg.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 31 14:35:16 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StyleLovVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        StyleName {
            public Object get(StyleLovVORowImpl obj) {
                return obj.getStyleName();
            }

            public void put(StyleLovVORowImpl obj, Object value) {
                obj.setStyleName((String)value);
            }
        }
        ,
        Brand {
            public Object get(StyleLovVORowImpl obj) {
                return obj.getBrand();
            }

            public void put(StyleLovVORowImpl obj, Object value) {
                obj.setBrand((String)value);
            }
        }
        ,
        Season {
            public Object get(StyleLovVORowImpl obj) {
                return obj.getSeason();
            }

            public void put(StyleLovVORowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        CustomerId {
            public Object get(StyleLovVORowImpl obj) {
                return obj.getCustomerId();
            }

            public void put(StyleLovVORowImpl obj, Object value) {
                obj.setCustomerId((Number)value);
            }
        }
        ,
        CustomerName {
            public Object get(StyleLovVORowImpl obj) {
                return obj.getCustomerName();
            }

            public void put(StyleLovVORowImpl obj, Object value) {
                obj.setCustomerName((String)value);
            }
        }
        ,
        RecipeNo {
            public Object get(StyleLovVORowImpl obj) {
                return obj.getRecipeNo();
            }

            public void put(StyleLovVORowImpl obj, Object value) {
                obj.setRecipeNo((String)value);
            }
        }
        ,
        VersionNo {
            public Object get(StyleLovVORowImpl obj) {
                return obj.getVersionNo();
            }

            public void put(StyleLovVORowImpl obj, Object value) {
                obj.setVersionNo((String)value);
            }
        }
        ,
        CustomerNameD {
            public Object get(StyleLovVORowImpl obj) {
                return obj.getCustomerNameD();
            }

            public void put(StyleLovVORowImpl obj, Object value) {
                obj.setCustomerNameD((String)value);
            }
        }
        ,
        BuyerName {
            public Object get(StyleLovVORowImpl obj) {
                return obj.getBuyerName();
            }

            public void put(StyleLovVORowImpl obj, Object value) {
                obj.setBuyerName((String)value);
            }
        }
        ,
        CurrentStyle {
            public Object get(StyleLovVORowImpl obj) {
                return obj.getCurrentStyle();
            }

            public void put(StyleLovVORowImpl obj, Object value) {
                obj.setCurrentStyle((String)value);
            }
        }
        ,
        CurrentSeason {
            public Object get(StyleLovVORowImpl obj) {
                return obj.getCurrentSeason();
            }

            public void put(StyleLovVORowImpl obj, Object value) {
                obj.setCurrentSeason((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(StyleLovVORowImpl object);

        public abstract void put(StyleLovVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int STYLENAME = AttributesEnum.StyleName.index();
    public static final int BRAND = AttributesEnum.Brand.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int RECIPENO = AttributesEnum.RecipeNo.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int CUSTOMERNAMED = AttributesEnum.CustomerNameD.index();
    public static final int BUYERNAME = AttributesEnum.BuyerName.index();
    public static final int CURRENTSTYLE = AttributesEnum.CurrentStyle.index();
    public static final int CURRENTSEASON = AttributesEnum.CurrentSeason.index();

    /**
     * This is the default constructor (do not remove).
     */
    public StyleLovVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute StyleName.
     * @return the StyleName
     */
    public String getStyleName() {
        return (String) getAttributeInternal(STYLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StyleName.
     * @param value value to set the  StyleName
     */
    public void setStyleName(String value) {
        setAttributeInternal(STYLENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Brand.
     * @return the Brand
     */
    public String getBrand() {
        return (String) getAttributeInternal(BRAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Brand.
     * @param value value to set the  Brand
     */
    public void setBrand(String value) {
        setAttributeInternal(BRAND, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Season.
     * @return the Season
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Season.
     * @param value value to set the  Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerId.
     * @return the CustomerId
     */
    public Number getCustomerId() {
        return (Number) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerId.
     * @param value value to set the  CustomerId
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName.
     * @param value value to set the  CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RecipeNo.
     * @return the RecipeNo
     */
    public String getRecipeNo() {
        return (String) getAttributeInternal(RECIPENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RecipeNo.
     * @param value value to set the  RecipeNo
     */
    public void setRecipeNo(String value) {
        setAttributeInternal(RECIPENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VersionNo.
     * @return the VersionNo
     */
    public String getVersionNo() {
        return (String) getAttributeInternal(VERSIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VersionNo.
     * @param value value to set the  VersionNo
     */
    public void setVersionNo(String value) {
        setAttributeInternal(VERSIONNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerNameD.
     * @return the CustomerNameD
     */
    public String getCustomerNameD() {
        return (String) getAttributeInternal(CUSTOMERNAMED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerNameD.
     * @param value value to set the  CustomerNameD
     */
    public void setCustomerNameD(String value) {
        setAttributeInternal(CUSTOMERNAMED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerName.
     * @return the BuyerName
     */
    public String getBuyerName() {
        return (String) getAttributeInternal(BUYERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerName.
     * @param value value to set the  BuyerName
     */
    public void setBuyerName(String value) {
        setAttributeInternal(BUYERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentStyle.
     * @return the CurrentStyle
     */
    public String getCurrentStyle() {
        return (String) getAttributeInternal(CURRENTSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentStyle.
     * @param value value to set the  CurrentStyle
     */
    public void setCurrentStyle(String value) {
        setAttributeInternal(CURRENTSTYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentSeason.
     * @return the CurrentSeason
     */
    public String getCurrentSeason() {
        return (String) getAttributeInternal(CURRENTSEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentSeason.
     * @param value value to set the  CurrentSeason
     */
    public void setCurrentSeason(String value) {
        setAttributeInternal(CURRENTSEASON, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
