package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 08 13:12:32 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SubProcessPopUpVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SubProcessPopUpVOImpl() {
    }
}
