package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 07 16:31:47 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WashingWorkAreaImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WashingWorkAreaImpl() {
    }


}
